Updated to new API methods (zips/create)
AjayBrahmakshatriya/put-cli pull request #10
Opened 2017-12-15 15:17 UTC by floriscornel

And added unzipped downloading for single files.

2017-12-17 15:38 UTC, AgamAgarwal commented on src/put
> +		download_command = config_json["downloader"].replace("$1", ".").replace("$2", file_names[0]).replace("$3", download_url)
Now that constructing the download_command is done in multiple places (here and line 299), I would recommend pulling it out into a function.

2017-12-17 15:38 UTC, AgamAgarwal commented on src/put
> +		print(download_command)
I am assuming this was for debugging. If yes, please remove this.

2017-12-17 15:41 UTC, AgamAgarwal requested changes
Hi Floris,
We are happy to see that someone other than us is actually using this tool. 😛 

Thanks a lot for the PR. Left a few minor comments. I will merge this PR once you resolve them.

Thanks a lot.

2017-12-17 19:06 UTC, floriscornel commented
Hi Agam,
Thanks for the feedback, I have updated my code.

I was looking at a few cli put.io projects on GitHub and this one seemed most up to date, I might add some other features in the future like searching.

2017-12-18 18:17 UTC, AgamAgarwal approved these changes

2017-12-18 18:18 UTC, AgamAgarwal commented
Sure thing. Feel free to send more PRs.

2017-12-18 18:19 UTC, merged